config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'comments/index'
  end
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }
  
  namespace :admin do
    get 'dashboards', to: 'dashboards#index'
    resources :users, only: [:index, :destroy]
    resources :comments, only: [:index, :destroy]
  end

  root to: 'homes#top'
  get '/about', to: 'homes#about', as: 'about'
  get "search_tag" => "parks#search_tag" 
  resources :parks do
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update, :create, :index]
  resources :comments, only: [:create, :destroy]
end

app/models/park.rb
class Park < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  def favorited?(user)
     favorites.where(user_id: user.id).exists?
  end
  
  def save_tag(sent_tags)
      current_tags = self.tags.pluck(:name) unless self.tags.nil?
      old_tags = current_tags - sent_tags
      new_tags = sent_tags - current_tags
    
      old_tags.each do |old|
        self.tags.delete　Tag.find_by(name: old)
      end
    
      new_tags.each do |new|
        new_post_tag = Tag.find_or_create_by(name: new)
        self.post_tags.find_or_create_by(tag_id: new_post_tag.id)
     end
  end

  validates :park_name, presence:true
  validates :address, presence: true

  geocoded_by :address
  after_validation :geocode
end

app/controllers/parks_controller.rb
class ParksController < ApplicationController
  def new
    @park = Park.new
  end

  def create
    @park = Park.new(park_params)
    @park.user_id = current_user.id
    tag_list = params[:park][:name].split(',')
    if @park.save
      @park.save_tag(tag_list)
      flash[:notice] = '公園の情報を投稿しました。'
      redirect_to parks_path
    else
      flash.now[:alert] = '投稿に失敗ました。'
      @parks = Park.all
      render :new
    end
  end

  def index
    @parks = Park.all
    @parks = Park.order(created_at: :desc).page(params[:page]).per(7)
    
    if params[:address_keyword].present?
      @parks = @parks.where("address LIKE ?", "%#{params[:address_keyword]}%")
    elsif params[:park_name_keyword].present?
      @parks = @parks.where("park_name LIKE ?", "%#{params[:park_name_keyword]}%")
    end
    
    @tag_list = Tag.all
    @parks = @parks.includes(:post_tags).where('post_tags.tag_id': params[:tag_id]) if params[:tag_id].present?
    
    respond_to do |format|
      format.html do
        @parks
      end
      format.json do
        @parks
      end
    end
  end
  
  def search_tag
    @tag_list=Tag.all
    @tag=Tag.find(params[:tag_id])
    @parks=@tag.parks.page(params[:page]).per(10)
  end

  def show
    respond_to do |format|
      format.html do
        @park = Park.find(params[:id])
        @user = User.find(@park.user.id)
      end
      format.json do
        @park = Park.find(params[:id])
      end
    end
    @comments = @park.comments
    @comments = Comment.where(park_id: @park.id).order(created_at: :desc)
    @comment = Comment.new
    @park_favorites_count = Favorite.where(park_id: @park.id).count
    @post_tags = @park.tags
  end

  def edit
    is_matching_login_user
    @park = Park.find(params[:id])
    @tag_list = @park.tags.pluck(:name).join(',')
  end

  def update
    is_matching_login_user
    @park = Park.find(params[:id])
    tag_list = params[:park][:name].split(',')
    if @park.update(park_params)
      @park.save_tag(tag_list)
      flash[:notice] = '公園の情報を更新しました。'
      redirect_to park_path(@park)
    else
      render :edit
    end
  end


  def destroy
    @park = Park.find(params[:id])
    if @park.destroy
      flash[:notice] = '公園の情報を削除しました。'
      redirect_to parks_path
    else
    end
  end

  private

  def park_params
    params.require(:park).permit(:park_name, :park_introduction, :address, :image, :star)
  end
  
  def is_matching_login_user
    park = Park.find(params[:id])
    unless park.user.id == current_user.id
      redirect_to parks_path
    end
  end

end

app/helpers/parks_helper.rb
module ParksHelper
end

app/views/parks/_form.html.erb
<%= form_with model: @park, url: @park.new_record? ? parks_path : park_path(@park), method: @park.new_record? ? :post : :patch do |f| %>
  <h4>公園名称</h4>
  <div class="mt-3 mb-3">
    <%= f.text_field :park_name, class: 'form-control' %>
  </div>
  <h4>評価</h4>
  <div class="mt-3 mb-3" id="star">
    <%= f.hidden_field :star, class: 'form-control' %>
    <div id="post_raty"></div>
  </div>
  <script>
    $('#post_raty').empty();
    $('#post_raty').raty({  
      starOn: "<%= asset_path('star-on.png') %>",
      starOff: "<%= asset_path('star-off.png') %>",
      starHalf: "<%= asset_path('star-half.png') %>",
      scoreName: 'park[star]',
      score: "<%= f.object.star %>"
    });
  </script>

  <h4>場所</h4>
  <div class="input-group mb-3 mt-4">
    <div class="input-group-prepend">
      <span class="input-group-text" aria-hidden="true"><i class="fa-solid fa-tenge-sign"></i></span>
    </div>
    <%= text_field_tag :zipcode, nil, class: "form-control", placeholder: "郵便番号", id: "zipcode" %>
  </div>
  <div class="input-group mb-3 mt-4">
    <div class="input-group-prepend">
      <span class="input-group-text" aria-hidden="true"><i class="fa-solid fa-location-dot"></i></span>
    </div>
    <%= f.text_field :address, class: "form-control", placeholder: "住所", id: "post_image_address" %>
  </div>

  <h4>画像アップロード</h4>
    <div class="form-group mt-3 mb-3">
      <%= f.file_field :image %>
    </div>

  <h4>タグ付け</h4>
    <div class="form_group mb-3 mt-3">
      <%= f.label"タグ (,で区切ると複数タグ登録できます)" %>
      <%= f.text_field :name,value: @tag_list,class:"form-control"%>
    </div>    
  <h4>公園紹介</h4>
    <div class="form-group mb-3 mt-3">
      <%= f.text_area :park_introduction, class: 'form-control' %><br>
    </div>
    
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

<%= javascript_pack_tag "jpostal",  'data-turbolinks-track': 'reload' %>

app/views/parks/edit.html.erb
<div class="row">
  <div class="col-6 mt-3 pb-3 text-left">
    <%= link_to "ホーム", parks_path %> >> <%= link_to @park.park_name, park_path(@park.id) %> >> 投稿編集
  </div>
</div>

<% if @park.errors.any? %>
  <%= @park.errors.count %>error prohibited this pk from being saved:
  <ul>
    <% @park.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="row">
  <div class="col-10 offset-1 card mt-3">
    <div class="card-body">
      <h2 class="mb-5 d-flex justify-content-center">投稿編集フォーム</h2>
      <%= render "form", park: @park %>
    </div>
  </div>
</div>
  
<style>
  .card {
    background-color: #F7EAAD;
  }
</style>
    

app/views/parks/index.html.erb
<style>
  .card {
    background-color: #f7eaad;
  }
  
  
</style>


  <div class="row">
    <div class="col-3 mt-3 text-left">
      <span>ホーム</span>
    </div>
  </div>

  <br>
  <br>
  
  <div class="card mt-2">
    <h3 class="search mt-2 ml-3"><i class="fa-solid fa-magnifying-glass"></i>検索フォーム</h3>
    <div class="row">
      <div class="col-4 mb-5 offset-2">
        <div>
        <%= form_with url: parks_path, method: :get do |f| %>
          <div class="form-label mt-3 texe-left">
            <%= f.label :search, "エリアで検索" %>
          </div>
          <%= f.search_field :address_keyword, value: params[:address_keyword] %>
          <%= f.submit "検索" %>
        <% end %>
        </div>
      </div>
      
      <div class="col-4 ml-3 mb-3">
        <div>
          <%= form_with url: parks_path, method: :get do |f| %>
            <div class="form-label  mt-3 texe-left">
              <%= f.label :search, "公園名で検索" %>
            </div>
            <%= f.search_field :park_name_keyword, value: params[:park_name_keyword] %>
            <%= f.submit "検索" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="row mt-5">
    <div class="col-md-3">
      <div class="card">
        <h3 class="tags mt-2 ml-3"><i class="fa-solid fa-tags"></i>タグ検索</h3>
        <div class="mb-5">
          <ul style="list-style:none;">
            <% @tag_list.each do |list|%>
              <li>
                <%= link_to list.name, parks_path(tag_id: list.id) %>
                <%= "(#{list.parks.count})" %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  
    <div class="col-md-6">
      <div id="map" style="height:50vh;" class="mt-2"></div>
    </div>
  
    <div class="col-md-3">
      <div class="card mt-2">
        <h3 class="posts mt-2 ml-3"><i class="fa-solid fa-location-dot"></i>投稿一覧</h3>
        <table class="table table-light">
          <thead>
            <tr>
              <th>投稿日</th>
              <th>公園名</th>
            </tr>
          </thead>
          <tbody>
            <% @parks.each do |park| %>
              <tr>
                <td><%= l park.created_at %></td>
                <td><%= link_to park.park_name, park_path(park.id) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <div class="d-flex justify-content-center">
          <%= paginate @parks %>
        </div>
      </div>
    </div>
  </div>
</div>

<%= javascript_pack_tag 'map_index', 'data-turbolinks-track': 'reload' %>

app/views/parks/new.html.erb
<div class="row">
  <div class="col-5 mt-3 mb-3 text-left">
    <%= link_to "ホーム", parks_path %> >> 新規投稿
  </div>
</div>

<% if @park.errors.any? %>
  <h2>
    <%= I18n.t("errors.messages.not_saved",
        count: @park.errors.count,
        resource: @park.class.model_name.human.downcase)
    %>
  </h2>
  <ul>
    <% @park.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="row">
  <div class="col-10 offset-1 card mt-3">
    <div class="card-body">
      <h2 class="mb-5 d-flex justify-content-center">新規投稿フォーム</h2>
      <%= render "form", park: @park %>
    </div>
  </div>
</div>
  
<style>
  .card {
    background-color: #F7EAAD;
  }
</style>
    

app/views/parks/show.html.erb
<style>
  .no-underline:hover {
    text-decoration: none;
  }
  
</style>


<div class="row">
  <div class="col-5 mt-3 text-left">
    <%= link_to "ホーム", parks_path %> >> <%= @park.park_name %>
  </div>
</div>

<div class="row">
  <div class="col-8 mt-3">
    
    <div style="display: flex; align-items: center;">
      <h2 style="margin-right: 20px;"><%= @park.park_name %></h2>
        <% if @park.user_id == current_user.id %>
        <%= link_to "投稿を編集", edit_park_path(@park.id), class: "btn btn-success mr-2" %> ／
        <%= link_to '投稿を削除', @park, method: :delete, data: { confirm: '本当に削除しますか?' }, class: "btn btn-danger ml-2" %>
        <% end %>
    </div>
    
    <div id="star_<%= @park.id %>", style="margin-top: 20px;"></div>
    <script>
      $('#star_<%= @park.id %>').empty();
      $('#star_<%= @park.id %>').raty({  
        starOn: "<%= asset_path('star-on.png') %>",
        starOff: "<%= asset_path('star-off.png') %>",
        starHalf: "<%= asset_path('star-half.png') %>",
        score: "<%= @park.star %>",
        readOnly: true,
      });
    </script>
  </div>

  
  <div class="col-4 mt-4 text-right">
    投稿ユーザー:<%= image_tag(@park.user.profile_image, size: "50x50", class: "avatar rounded-circle") if @park.user.profile_image? %>
    <%= link_to @park.user.name, user_path(@park.user) %>
  </div>
</div>


<div class="row" id="mapInfo" data-parkId=<%= @park.id %>>
  <div class="col-md-6 mt-4 d-flex align-items-center text-center">
    <% if @park.image.attached? %>
      <%= image_tag @park.image.variant(resize: '500x') %>
    <% else %>
      <%= image_tag 'noimage.png', size: '200x200', class: 'mx-auto' %>
    <% end %>
  </div>
  
  <div class="col-md-6">
    <div id="map", class="mt-4"></div>
  </div>
</div>
      
<h3 class='tags mt-3'>タグ</h3>
<div class="row">
  <% @post_tags.each do |tag| %>
    <%= link_to tag.name, parks_path(tag_id: tag.id) %>
    <%= "(#{tag.parks.count})" %>
  <% end %>
</div>

<h3 class="introduction mt-3">公園紹介</h3>
<div class="row">
  <div class="col-6 pt-3 pb-3 border border-dark rounded-2">
    <%= simple_format(@park.park_introduction, sanitize: true) %>
  </div>
</div>
  
<div class="row">
  <p class="mt-3 mb-3">
    <% if @park.favorited?(current_user) %>
        <%= link_to park_favorites_path(@park.id), method: :delete, class: 'no-underline' do %>
           <i class="fa-solid fa-thumbs-up", style="color:red;"></i>
        <% end %>いいね
    <% else %>
        <%= link_to park_favorites_path(@park.id), method: :post, class: 'no-underline' do %>
          　<i class="fa-solid fa-thumbs-up"></i>
        <% end %>いいね
            
    <% end %>
    <%= @park_favorites_count %>
  </p>
</div>
  
<div class="row">
  <div class="col-md-7">
    <div id="comment_button" class="btn btn-primary show">コメント</div>
    <ul id="comments_area" class="hide">
      <% @comments.each do |comment| %>
        <li><%= comment.comment %> ：by <%= comment.user.name %> - <%= comment.created_at.strftime("%Y-%m-%d %H:%M:%S") %>
        <%= link_to '削除', comment_path(comment), method: :delete, data: { confirm: '本当に削除しますか？' }, class: 'btn btn-sm btn-danger' if current_user == comment.user %></li>
      <% end %>
      <div id="close_button" class="btn btn-success">---コメントを閉じる---</div>
    </ul>
  </div>
  
  <div class="col-md-5">
    <%= form_with model: @comment do |f| %>
      <%= f.hidden_field :park_id, value: @park.id %>
      <%= f.text_area :comment, class: "form-control" %>
      <%= f.submit "コメントする" %>
    <% end %>
  </div>
</div>

<%= javascript_pack_tag 'map_show', 'data-turbolinks-track': 'reload' %>

<style>
  #comments_area {
    list-style: ;
  }
  .show {
    display: inline-block;
  }
  .hide {
    display: none;
  }
</style>

<script>
  $('#comment_button').on('click', () => {
    $('#comments_area').removeClass('hide').addClass('show')
    $('#comment_button').removeClass('show').addClass('hide')
  })
  
  $('#close_button').on('click', () => {
    $('#comments_area').removeClass('show').addClass('hide')
    $('#comment_button').removeClass('hide').addClass('show')
  })
</script>