config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'comments/index'
  end
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }
  
  namespace :admin do
    get 'dashboards', to: 'dashboards#index'
    resources :users, only: [:index, :destroy]
    resources :comments, only: [:index, :destroy]
  end

  root to: 'homes#top'
  get '/about', to: 'homes#about', as: 'about'
  get "search_tag" => "parks#search_tag" 
  resources :parks do
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update, :create, :index]
  resources :comments, only: [:create, :destroy]
end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < ApplicationController

    
    before_action :authenticate_admin!
    
    def index
        @users = User.all
        @users = @users.where('name LIKE(?)', "%#{params[:keyword]}%") if params[:keyword].present?
    end
end

app/helpers/admin/dashboards_helper.rb
module Admin::DashboardsHelper
end

app/views/admin/dashboards/index.html.erb
<div class="row">
  <div class="ml-3 mt-3 mb-3">
    <%= link_to "ログアウト", destroy_admin_session_path, method: :delete %>
  </div>
</div>

<h1>全ユーザー一覧</h1>


<div class="row">
  <div class="col-md-2">
    <%= render 'admin/shared/dashboard_buttons' %>
  </div>
  <div class="col-md-10">
    <%= form_with url: admin_dashboards_path, method: :get do |f| %>
      <%= f.search_field :keyword, value: params[:keyword] %>
    
      <%= f.submit "search" %>
    <% end %>
    
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>id</th>
          <th>email</th>
          <th>name</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.id %></td>
            <td><%= user.email %></td>
            <td><%= user.name %></td>
            <td><%= link_to '削除', admin_user_path(user), method: :delete, data: { confirm: '本当に削除しますか？' }, class: "btn btn-danger" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>