config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'comments/index'
  end
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }
  
  namespace :admin do
    get 'dashboards', to: 'dashboards#index'
    resources :users, only: [:index, :destroy]
    resources :comments, only: [:index, :destroy]
  end

  root to: 'homes#top'
  get '/about', to: 'homes#about', as: 'about'
  get "search_tag" => "parks#search_tag" 
  resources :parks do
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update, :create, :index]
  resources :comments, only: [:create, :destroy]
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Admin - Meshiterro</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <% if admin_signed_in? %>
    <div class="text-right">
      <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete %>
    </div>
  <% end %>
  <%= yield %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dokoikopark</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/d78874b31e.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <link href="https://fonts.googleapis.com/css2?family=M+PLUS+1+Code:wght@100..700&display=swap" rel="stylesheet">
  </head>

  <body class="d-flex flex-column vh-100">
    <header>
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand" href="/">
            <%= image_tag 'logo.png', width: 200, height: 100, alt:'サイトロゴ' %>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <div class="mt-2 text-black">
              <%= image_tag(current_user.get_profile_image(50, 50), alt: current_user.name, class: "avatar rounded-circle") %>
              ようこそ、<%= current_user.name %>さん！
            </div>
            <li>
              <%= link_to user_path(current_user.id), class: "nav-link text-dark" do %>
              <i class="fa-solid fa-user"></i> マイページ
              <% end %>
            </li>
            <li>
              <%= link_to new_park_path, class: "nav-link text-dark", data: {turbolinks: "false"} do %>
              <i class="fa-solid fa-pencil"></i> 新規投稿
              <% end %>
            </li>
            <li>
              <%= link_to parks_path, class: "nav-link text-dark" do %>
              <i class="fa-solid fa-location-dot"></i> 投稿一覧
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-dark" do %>
              <i class="fa-solid fa-right-from-bracket"></i> ログアウト
              <% end %>
            </li>
            <% else %>
            <li>
              <%= link_to root_path, class: "nav-link text-dark" do %>
              <i class="fa-solid fa-house"></i> ホーム
              <% end %>
            </li>
            <li>
              <%= link_to about_path, class: "nav-link text-dark" do %>
              <i class="fa-solid fa-link"></i> このサイトについて
              <% end %>
            </li>
            <li>
              <%= link_to new_user_registration_path, class: "nav-link text-dark" do %>
              <i class="fa-solid fa-user-plus"></i> 新規登録
              <% end %>
            </li>
            <li>
              <%= link_to new_user_session_path, class: "nav-link text-dark" do %>
              <i class="fa-solid fa-right-to-bracket"></i> ログイン
              <% end %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <div class="container">
    <%= yield %>
    </div>
    <footer class="footer text-light">
      <div class="container mt-2 mb-2 text-dark text-center"> ©2024 Sho_n.
      </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/jquery-jpostal-ja@2.14.45/jquery.jpostal.min.js"></script>
  </body>
</html>